lane :test do
  increment_bundle_version(info_plist: "Info.plist", version_number: "1.0", build_number: "1", auto_increment: true)
  increment_version_code(manifest: "AndroidManifest.xml", version_name: "1.0", version_code: "1", auto_increment: true)
end
